### ISSUE TITLE
Extension of image deps for JavaScript

### ISSUE THREAD

**Issue by raisultan** [glotcode/glot-images#1]
Hi! Great project. Is there any way to add npm packages [jest, axios] to javascript image, specifically to nix build config for javascript? I am trying to create my own images, due to the absence of some packages in the base images and use them with the code-runner.

**Comment by prasmussen** [comment]
I added jest and axios to the javascript image in [this commit](https://github.com/glotcode/glot-images/commit/ea8a1e5a96edd551fb1ad9d29c226b7f41cc3918).
Here is a snippet to see jest in action: https://glot.io/snippets/fx4azwqeie

To add more deps you can use `yarn add` and then run `yarn2nix > yarn.nix`.

**Comment by raisultan** [comment]
Awesome! Got it. Thank you.
