### ISSUE TITLE
Making HTTP request from language container

### ISSUE THREAD

**Issue by raisultan** [glotcode/glot-images#2]
Hi, thanks for great work. I am having issue with making HTTP requests from inside of a programming language container, is it possible? For instance, I am trying to make plain request with Python:
```python
# Request
import urllib.request

with urllib.request.urlopen('http://python.org/') as response:
    html = response.read()

# Error
urllib.error.URLError: <urlopen error [Errno -2] Name or service not known>
```

**Comment by prasmussen** [comment]
Hey, network is disabled on glot.io for security reasons. I might introduce a paid plan with network access if there are enough interest.
